listen_addresses = '*'
port = 5432
ssl = on
ssl_cert_file = '/certs/server.crt'
ssl_key_file = '/certs/server.key'
ssl_min_protocol_version = 'TLSv1.2'
hba_file = '/config/pg_hba.conf'
password_encryption = 'scram-sha-256'
max_connections = 40
shared_buffers = '128MB'
work_mem = '4MB'
maintenance_work_mem = '64MB'
effective_cache_size = '512MB'
min_wal_size = '80MB'
max_wal_size = '256MB'
logging_collector = off
log_statement = 'none'
log_min_error_statement = panic
timezone = 'UTC'
