services:
  app:
    build:
      context: .
    env_file:
      - .env.local
    environment:
      HOST: 0.0.0.0
      NODE_ENV: production
      PORT: 3000
    ports:
      - "3000:3000"
    restart: unless-stopped
    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
